---
title: "central_task"
format: html
---
## Libraries and settings required for analysis
```{r setup}
library(tidyverse)

library(cmdstanr)
library(fs)
library(ggtext)
library(glue)
library(kilter) # devtools:install_github("alexander-pastukhov/kilter", dependencies=TRUE)
library(loo)
library(patchwork)

source("utils.R")
```

## import parameter distributions
```{r}
p01 <- readRDS("central_task/exp01.RDS") |>
  mutate(exp = "Exp1",
         Participant = factor(Participant, labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)))
p02 <- readRDS("central_task/exp02.RDS") |>
  mutate(exp = "Exp2",
         Participant = factor(Participant, labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)))
p03 <- readRDS("central_task/exp03.RDS") |>
  mutate(exp = "Exp3",
         Participant = factor(Participant, labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)))

ct <- 
  bind_rows(p01, p02, p03) |>
  mutate(exp = factor(exp))
```

```{r}
Pcorrect <- ggplot(ct|> filter (Parameter == "Pcorrect"), aes(x = Participant, y = mu)) +
  geom_point()+
  geom_errorbar(aes(ymin = LowerCI, ymax = UpperCI))+
  geom_hline(yintercept = 0.5, linetype = "dashed")+
  facet_grid(Parameter ~ exp)

rt <- ggplot(ct|> filter (Parameter == "avgRT"), aes(x = Participant, y = mu)) +
  geom_point()+
  geom_errorbar(aes(ymin = LowerCI, ymax = UpperCI))+
  #geom_hline(yintercept = 0.5, linetype = "dashed")+
  facet_grid(Parameter ~ exp)

Pcorrect / rt + 
    plot_layout(guides = 'collect', axis_titles = "collect")

ggsave("central_task/plot_ct.png", units = "cm", width = 17, height = 12)
#ggsave("Figures/weights.svg", units = "cm", width = 17, height = 17)
```